[2025-04-30T13:24:14.727+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias_orgaos_responsaveis.extrair_dados_ocorrencias_orgaos_responsaveis manual__2025-04-30T13:24:14.162935+00:00 [queued]>
[2025-04-30T13:24:14.732+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: adm_cor_comando_ocorrencias_orgaos_responsaveis.extrair_dados_ocorrencias_orgaos_responsaveis manual__2025-04-30T13:24:14.162935+00:00 [queued]>
[2025-04-30T13:24:14.732+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-30T13:24:14.741+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extrair_dados_ocorrencias_orgaos_responsaveis> on 2025-04-30 13:24:14.162935+00:00
[2025-04-30T13:24:14.745+0000] {standard_task_runner.py:60} INFO - Started process 260 to run task
[2025-04-30T13:24:14.747+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'adm_cor_comando_ocorrencias_orgaos_responsaveis', 'extrair_dados_ocorrencias_orgaos_responsaveis', 'manual__2025-04-30T13:24:14.162935+00:00', '--job-id', '239', '--raw', '--subdir', 'DAGS_FOLDER/adm_cor_comando.py', '--cfg-path', '/tmp/tmpl4gq98qd']
[2025-04-30T13:24:14.749+0000] {standard_task_runner.py:88} INFO - Job 239: Subtask extrair_dados_ocorrencias_orgaos_responsaveis
[2025-04-30T13:24:14.785+0000] {task_command.py:423} INFO - Running <TaskInstance: adm_cor_comando_ocorrencias_orgaos_responsaveis.extrair_dados_ocorrencias_orgaos_responsaveis manual__2025-04-30T13:24:14.162935+00:00 [running]> on host 81c910e0b178
[2025-04-30T13:24:14.849+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='adm_cor_comando_ocorrencias_orgaos_responsaveis' AIRFLOW_CTX_TASK_ID='extrair_dados_ocorrencias_orgaos_responsaveis' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T13:24:14.162935+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-30T13:24:14.162935+00:00'
[2025-04-30T13:24:14.851+0000] {logging_mixin.py:188} INFO - Extraindo dados da URL: https://api.dados.rio/v2/adm_cor_comando/ocorrencias_orgaos_responsaveis/
[2025-04-30T13:24:15.326+0000] {logging_mixin.py:188} INFO - [ERRO] Falha na extração: 400 Client Error: Bad Request for url: https://api.dados.rio/v2/adm_cor_comando/ocorrencias_orgaos_responsaveis/
[2025-04-30T13:24:15.328+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-30T13:24:15.334+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=adm_cor_comando_ocorrencias_orgaos_responsaveis, task_id=extrair_dados_ocorrencias_orgaos_responsaveis, execution_date=20250430T132414, start_date=20250430T132414, end_date=20250430T132415
[2025-04-30T13:24:15.361+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-30T13:24:15.378+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
